export const poeple = [
  {
    id: "1c7e9df4-8c30-4b84-9055-18f462b11115",
    name: "John Doe",
    email: "john.doe@example.com",
    generation: "gen Y",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "TechCorp",
    stack: "Frontend",
  },
  {
    id: "6f1ed8b2-2d37-4f87-953d-6f1d1c9e4c76",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    generation: "gen X",
    hometown: "Haifa",
    livingTown: "Beersheba",
    company: "Innovatech",
    stack: "Backend",
  },
  {
    id: "bfbf7f1d-87cf-464e-b9d8-742a2c5c8f2b",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    generation: "Baby Boomers",
    hometown: "Eilat",
    livingTown: "Ashdod",
    company: "BuildIt",
    stack: "Full Stack",
  },
  {
    id: "43780e55-0458-4b32-9eb6-94ad6d8a74ec",
    name: "Bob Brown",
    email: "bob.brown@example.com",
    generation: "gen Z",
    hometown: "Jerusalem",
    livingTown: "Tel Aviv",
    company: "SoftSolutions",
    stack: "Frontend",
  },
  {
    id: "7b4f7d58-c5b2-4c5b-95f1-e5402b8d5e6b",
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    generation: "gen X",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "CodeFactory",
    stack: "Backend",
  },
  {
    id: "27f2e8b7-69d3-4d71-8b7c-441f2d6a1f75",
    name: "Diana Evans",
    email: "diana.evans@example.com",
    generation: "gen Y",
    hometown: "Beersheba",
    livingTown: "Eilat",
    company: "WebMasters",
    stack: "Human",
  },
  {
    id: "d0f2a3e6-d6d2-4b4b-8b7e-2f2d1d3a1f75",
    name: "Michael Green",
    email: "michael.green@example.com",
    generation: "gen Z",
    hometown: "Tel Aviv",
    livingTown: "Ashdod",
    company: "BrightSolutions",
    stack: "Full Stack",
  },
  {
    id: "8a7e9c1d-3b2d-4e7e-9c2b-8a1d3b4c5d2e",
    name: "Linda White",
    email: "linda.white@example.com",
    generation: "Baby Boomers",
    hometown: "Jerusalem",
    livingTown: "Beersheba",
    company: "FutureTech",
    stack: "Frontend",
  },
  {
    id: "6c3e8d2f-5a7d-4e8d-9b2e-5a1d3d4c7d2e",
    name: "David Harris",
    email: "david.harris@example.com",
    generation: "gen X",
    hometown: "Haifa",
    livingTown: "Eilat",
    company: "TechInnovators",
    stack: "Backend",
  },
  {
    id: "4a5d8f3e-7b2e-4d8e-9f2d-7b1d3e4c9d2e",
    name: "Barbara Martinez",
    email: "barbara.martinez@example.com",
    generation: "gen Y",
    hometown: "Ashdod",
    livingTown: "Tel Aviv",
    company: "CodeGurus",
    stack: "Human",
  },
  {
    id: "e2d6c4f2-8d9b-4b2e-97a7-2d4f2e6a7b9e",
    name: "James Wilson",
    email: "james.wilson@example.com",
    generation: "gen X",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "WebDevPro",
    stack: "Frontend",
  },
  {
    id: "3f4e8c1b-9d2f-4d8e-8f7d-4d2a7c5d3b8e",
    name: "Mary Garcia",
    email: "mary.garcia@example.com",
    generation: "Baby Boomers",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "NextGenTech",
    stack: "Backend",
  },
  {
    id: "b2d9e4f3-5b7d-4d8e-9f6d-5b1a4d7c6e2d",
    name: "Robert Thomas",
    email: "robert.thomas@example.com",
    generation: "gen Z",
    hometown: "Beersheba",
    livingTown: "Eilat",
    company: "SmartSolutions",
    stack: "Full Stack",
  },
  {
    id: "7c9d2e1a-8b2d-4f8e-9d1c-8a1b3d5c2e6a",
    name: "Patricia Anderson",
    email: "patricia.anderson@example.com",
    generation: "gen Y",
    hometown: "Jerusalem",
    livingTown: "Tel Aviv",
    company: "Innovatech",
    stack: "Human",
  },
  {
    id: "9d2a8f1c-3b2d-4e7e-9d2b-8a1d3c4f5d2b",
    name: "Jennifer Rodriguez",
    email: "jennifer.rodriguez@example.com",
    generation: "gen X",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "TechSolutions",
    stack: "Backend",
  },
  {
    id: "4d8e7f2a-5b2d-4e9e-9c3b-8a1d3e5d6f2e",
    name: "William Lewis",
    email: "william.lewis@example.com",
    generation: "gen Z",
    hometown: "Beersheba",
    livingTown: "Eilat",
    company: "FutureVision",
    stack: "Frontend",
  },
  {
    id: "8d2a6f3c-5b7d-4e9e-9d4b-8a1d3f5d7e2e",
    name: "Susan Clark",
    email: "susan.clark@example.com",
    generation: "Baby Boomers",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "BrightMinds",
    stack: "Full Stack",
  },
  {
    id: "5b2d7e3a-4c8d-4f9e-9d6b-8a1d3e5f7c2d",
    name: "Joseph Martinez",
    email: "joseph.martinez@example.com",
    generation: "gen Y",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "TechSavvy",
    stack: "Backend",
  },
  {
    id: "6d3a8f2b-7e5d-4d9e-9d7b-8a1d3e5f8c2e",
    name: "Sarah Lee",
    email: "sarah.lee@example.com",
    generation: "gen X",
    hometown: "Jerusalem",
    livingTown: "Beersheba",
    company: "Innovatech",
    stack: "Human",
  },
  {
    id: "d7a6f2b1-8c3d-4d9e-9d8b-8a1d3e6f9c2f",
    name: "Daniel Perez",
    email: "daniel.perez@example.com",
    generation: "gen Z",
    hometown: "Tel Aviv",
    livingTown: "Eilat",
    company: "TechPioneers",
    stack: "Frontend",
  },
  {
    id: "8c2e7d3f-6a5b-4e8e-9f2d-8a1d3e7d6c2e",
    name: "Jessica King",
    email: "jessica.king@example.com",
    generation: "Baby Boomers",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "NextGenTech",
    stack: "Backend",
  },
  {
    id: "4d9e6f3a-5b7d-4e8e-9c2b-8a1d3f6d8c2e",
    name: "David Hall",
    email: "david.hall@example.com",
    generation: "gen Y",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "BrightSolutions",
    stack: "Full Stack",
  },
  {
    id: "9c2d8f1e-4b3d-4d8e-9f7b-8a1d3e7f6c2e",
    name: "Karen Wright",
    email: "karen.wright@example.com",
    generation: "gen X",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "SmartTech",
    stack: "Human",
  },
  {
    id: "7d3a6f2b-4e9d-4d8e-9f2c-8a1d3e8f7c2e",
    name: "Matthew Young",
    email: "matthew.young@example.com",
    generation: "gen Z",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "TechSavvy",
    stack: "Frontend",
  },
  {
    id: "5a9e7f3c-8b3d-4d9e-9c1b-8a1d3e8f7c2d",
    name: "Lisa Allen",
    email: "lisa.allen@example.com",
    generation: "Baby Boomers",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "FutureVision",
    stack: "Backend",
  },
  {
    id: "8d7f6c3a-5b9d-4e9e-9f4b-8a1d3e7d9c2e",
    name: "Anthony Scott",
    email: "anthony.scott@example.com",
    generation: "gen Y",
    hometown: "Haifa",
    livingTown: "Beersheba",
    company: "Innovatech",
    stack: "Full Stack",
  },
  {
    id: "6c3a8f2d-7e9d-4d8e-9f5b-8a1d3e9f8c2e",
    name: "Brian Adams",
    email: "brian.adams@example.com",
    generation: "gen X",
    hometown: "Ashdod",
    livingTown: "Eilat",
    company: "CodeMasters",
    stack: "Human",
  },
  {
    id: "9d2e8f1b-4b7d-4e8e-9c6b-8a1d3e9f7c2e",
    name: "Nancy Baker",
    email: "nancy.baker@example.com",
    generation: "gen Z",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "TechInnovators",
    stack: "Frontend",
  },
  {
    id: "7e3a6f2b-4d9d-4d8e-9f7c-8a1d3e9f6c2e",
    name: "Paul Campbell",
    email: "paul.campbell@example.com",
    generation: "Baby Boomers",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "BrightSolutions",
    stack: "Backend",
  },
  {
    id: "6d2e8f1c-7a3d-4d9e-9f5c-8a1d3e9f7c2e",
    name: "Laura Phillips",
    email: "laura.phillips@example.com",
    generation: "gen Y",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "FutureTech",
    stack: "Full Stack",
  },
  {
    id: "5b7e8f3d-4d9d-4e8e-9c2d-8a1d3e9f6c2e",
    name: "Sandra Gonzalez",
    email: "sandra.gonzalez@example.com",
    generation: "gen X",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "TechPioneers",
    stack: "Human",
  },
  {
    id: "8c3a7f2b-5b9d-4d8e-9f7b-8a1d3e9f7c2e",
    name: "George Nelson",
    email: "george.nelson@example.com",
    generation: "gen Z",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "NextGenTech",
    stack: "Frontend",
  },
  {
    id: "7d2e9f3a-4b7d-4e9e-9f6b-8a1d3e8f7c2e",
    name: "Kevin Carter",
    email: "kevin.carter@example.com",
    generation: "Baby Boomers",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "BrightSolutions",
    stack: "Backend",
  },
  {
    id: "6a7e8f3d-5b9d-4d8e-9f3b-8a1d3e7f9c2e",
    name: "Betty Mitchell",
    email: "betty.mitchell@example.com",
    generation: "gen Y",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "TechInnovators",
    stack: "Full Stack",
  },
  {
    id: "9c3a8f2b-4d7d-4d8e-9f4c-8a1d3e8f6c2e",
    name: "Steven Perez",
    email: "steven.perez@example.com",
    generation: "gen X",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "FutureVision",
    stack: "Human",
  },
  {
    id: "7b2e9f3d-5a7d-4e8e-9c6d-8a1d3e7f6c2e",
    name: "Laura Roberts",
    email: "laura.roberts@example.com",
    generation: "gen Z",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "TechSavvy",
    stack: "Frontend",
  },
  {
    id: "6d3a8f2b-7e9d-4d8e-9f5b-8a1d3e9f8c2e",
    name: "Brian Adams",
    email: "brian.adams@example.com",
    generation: "gen X",
    hometown: "Ashdod",
    livingTown: "Eilat",
    company: "CodeMasters",
    stack: "Human",
  },
  {
    id: "9d2e8f1b-4b7d-4e8e-9c6b-8a1d3e9f7c2e",
    name: "Nancy Baker",
    email: "nancy.baker@example.com",
    generation: "gen Z",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "TechInnovators",
    stack: "Frontend",
  },
  {
    id: "7e3a6f2b-4d9d-4d8e-9f7c-8a1d3e9f6c2e",
    name: "Paul Campbell",
    email: "paul.campbell@example.com",
    generation: "Baby Boomers",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "BrightSolutions",
    stack: "Backend",
  },
  {
    id: "7a2e6f3b-4b9d-4e8e-9f1b-8a1d3e8f6c2e",
    name: "Emma Parker",
    email: "emma.parker@example.com",
    generation: "gen Y",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "NextGenTech",
    stack: "Full Stack",
  },
  {
    id: "5a8e7f2b-4d9d-4e8e-9f2c-8a1d3e7f9c2e",
    name: "Andrew Collins",
    email: "andrew.collins@example.com",
    generation: "gen X",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "FutureVision",
    stack: "Human",
  },
  {
    id: "9c2d7f3a-5b9d-4e8e-9c3b-8a1d3e6f7c2e",
    name: "Kathy Ramirez",
    email: "kathy.ramirez@example.com",
    generation: "gen Z",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "TechPioneers",
    stack: "Frontend",
  },
  {
    id: "7d3a6f2b-4e9d-4d8e-9f7c-8a1d3e9f7c2e",
    name: "Gary Edwards",
    email: "gary.edwards@example.com",
    generation: "Baby Boomers",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "BrightSolutions",
    stack: "Backend",
  },
  {
    id: "6b2d8f3a-4d9d-4e8e-9c1d-8a1d3e8f7c2e",
    name: "Marie Morgan",
    email: "marie.morgan@example.com",
    generation: "gen Y",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "TechInnovators",
    stack: "Full Stack",
  },
  {
    id: "8d3e7f2a-5b9d-4d8e-9f6b-8a1d3e7f8c2e",
    name: "Wayne Bell",
    email: "wayne.bell@example.com",
    generation: "gen X",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "FutureTech",
    stack: "Human",
  },
  {
    id: "9a7e8f2b-4d3d-4e9e-9f2c-8a1d3e6f7c2e",
    name: "Deborah Rivera",
    email: "deborah.rivera@example.com",
    generation: "gen Z",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "Innovatech",
    stack: "Frontend",
  },
  {
    id: "7b3d8f2a-4d9d-4e8e-9f3b-8a1d3e5f7c2e",
    name: "Brenda Cox",
    email: "brenda.cox@example.com",
    generation: "Baby Boomers",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "BrightSolutions",
    stack: "Backend",
  },
  {
    id: "6a8e7f3c-5b9d-4d8e-9c4d-8a1d3e4f7c2e",
    name: "Jason Howard",
    email: "jason.howard@example.com",
    generation: "gen Y",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "TechSavvy",
    stack: "Full Stack",
  },
  {
    id: "8b7e8f3a-4d9d-4e8e-9f5b-8a1d3e3f7c2e",
    name: "Pamela Ward",
    email: "pamela.ward@example.com",
    generation: "gen X",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "FutureVision",
    stack: "Human",
  },
  {
    id: "9d3a8f2b-5b7d-4e8e-9f6b-8a1d3e2f7c2e",
    name: "Linda Ross",
    email: "linda.ross@example.com",
    generation: "gen Z",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "TechPioneers",
    stack: "Frontend",
  },
  {
    id: "7a2e8f3d-4b9d-4d8e-9f7b-8a1d3e1f7c2e",
    name: "Eric Sanders",
    email: "eric.sanders@example.com",
    generation: "Baby Boomers",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "NextGenTech",
    stack: "Backend",
  },
  {
    id: "6b3d8f2a-4d9d-4e8e-9f1d-8a1d3e9f7c2e",
    name: "Kimberly Price",
    email: "kimberly.price@example.com",
    generation: "gen Y",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "BrightSolutions",
    stack: "Full Stack",
  },
  {
    id: "8d7e8f3a-5b9d-4d8e-9c3b-8a1d3e8f7c2e",
    name: "Ryan Brooks",
    email: "ryan.brooks@example.com",
    generation: "gen X",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "TechInnovators",
    stack: "Human",
  },
  {
    id: "9a3e8f2b-4b7d-4e8e-9f2b-8a1d3e9f7c2e",
    name: "Nicholas Wood",
    email: "nicholas.wood@example.com",
    generation: "gen Z",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "FutureTech",
    stack: "Frontend",
  },
  {
    id: "7e8a2f3c-4d9d-4e8e-9f1b-8a1d3e7f6c2e",
    name: "Nancy Bryant",
    email: "nancy.bryant@example.com",
    generation: "Baby Boomers",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "Innovatech",
    stack: "Backend",
  },
  {
    id: "6d3e8f2a-5b9d-4e8e-9f5c-8a1d3e6f7c2e",
    name: "Catherine Evans",
    email: "catherine.evans@example.com",
    generation: "gen Y",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "BrightSolutions",
    stack: "Full Stack",
  },
  {
    id: "9b2e7f3d-4b9d-4e8e-9c3d-8a1d3e5f7c2e",
    name: "Peter Cooper",
    email: "peter.cooper@example.com",
    generation: "gen X",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "TechSavvy",
    stack: "Human",
  },
  {
    id: "8a7e8f3a-5b9d-4e8e-9f6b-8a1d3e4f7c2e",
    name: "Emily Reed",
    email: "emily.reed@example.com",
    generation: "gen Z",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "BrightSolutions",
    stack: "Frontend",
  },
  {
    id: "7d3a9f2b-4b9d-4e8e-9f7c-8a1d3e3f7c2e",
    name: "Henry Butler",
    email: "henry.butler@example.com",
    generation: "Baby Boomers",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "NextGenTech",
    stack: "Backend",
  },
  {
    id: "6e3a8f2a-5b9d-4d8e-9f5d-8a1d3e6f7c2e",
    name: "Angela Adams",
    email: "angela.adams@example.com",
    generation: "gen Y",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "Innovatech",
    stack: "Full Stack",
  },
  {
    id: "5a8e7f2b-4d9d-4e8e-9f2c-8a1d3e7f9c2e",
    name: "Andrew Collins",
    email: "andrew.collins@example.com",
    generation: "gen X",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "FutureVision",
    stack: "Human",
  },
  {
    id: "8c7d9f2a-5b6d-4e8e-9f3b-8a1d3e5f7c2e",
    name: "Megan Rivera",
    email: "megan.rivera@example.com",
    generation: "gen Z",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "NextGenTech",
    stack: "Frontend",
  },
  {
    id: "7e3d8f2b-4b8d-4d8e-9f7c-8a1d3e6f7c2e",
    name: "Samuel Peterson",
    email: "samuel.peterson@example.com",
    generation: "Baby Boomers",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "Innovatech",
    stack: "Backend",
  },
  {
    id: "6a7e9f2b-5b8d-4e8e-9c4d-8a1d3e7f6c2e",
    name: "Angela Sanchez",
    email: "angela.sanchez@example.com",
    generation: "gen Y",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "BrightSolutions",
    stack: "Full Stack",
  },
  {
    id: "9d2e7f3b-4d9d-4e8e-9c6b-8a1d3e8f7c2e",
    name: "Ethan Jenkins",
    email: "ethan.jenkins@example.com",
    generation: "gen X",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "TechSavvy",
    stack: "Human",
  },
  {
    id: "8c3a6f2a-5b7d-4e8e-9f7b-8a1d3e9f7c2e",
    name: "Christine Scott",
    email: "christine.scott@example.com",
    generation: "gen Z",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "TechPioneers",
    stack: "Frontend",
  },
  {
    id: "7d2e8f2b-4b6d-4e8e-9f6b-8a1d3e7f8c2e",
    name: "Scott Phillips",
    email: "scott.phillips@example.com",
    generation: "Baby Boomers",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "FutureVision",
    stack: "Backend",
  },
  {
    id: "6b3d7f2a-5b8d-4e8e-9f1b-8a1d3e6f7c2e",
    name: "Lauren Cox",
    email: "lauren.cox@example.com",
    generation: "gen Y",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "NextGenTech",
    stack: "Full Stack",
  },
  {
    id: "9a2e8f3b-4b7d-4e8e-9f5c-8a1d3e5f7c2e",
    name: "Aaron Howard",
    email: "aaron.howard@example.com",
    generation: "gen X",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "TechInnovators",
    stack: "Human",
  },
  {
    id: "8d3e7f2a-5b8d-4e8e-9f4b-8a1d3e4f7c2e",
    name: "Sharon Sanders",
    email: "sharon.sanders@example.com",
    generation: "gen Z",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "BrightSolutions",
    stack: "Frontend",
  },
  {
    id: "7a3d8f2b-4d6d-4e8e-9f3d-8a1d3e3f7c2e",
    name: "Raymond Bell",
    email: "raymond.bell@example.com",
    generation: "Baby Boomers",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "Innovatech",
    stack: "Backend",
  },
  {
    id: "6e2e7f3a-5b8d-4e8e-9f7c-8a1d3e2f7c2e",
    name: "Frances Bailey",
    email: "frances.bailey@example.com",
    generation: "gen Y",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "NextGenTech",
    stack: "Full Stack",
  },
  {
    id: "9c3e8f2b-4b6d-4e8e-9f2b-8a1d3e1f7c2e",
    name: "Chris Rivera",
    email: "chris.rivera@example.com",
    generation: "gen X",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "BrightSolutions",
    stack: "Human",
  },
  {
    id: "8a2e7f3c-5b7d-4e8e-9c5d-8a1d3e0f7c2e",
    name: "Randy Parker",
    email: "randy.parker@example.com",
    generation: "gen Z",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "TechSavvy",
    stack: "Frontend",
  },
  {
    id: "7d3a8f2b-4b7d-4e8e-9f6b-8a1d3e9f7c2e",
    name: "Rachel Campbell",
    email: "rachel.campbell@example.com",
    generation: "Baby Boomers",
    hometown: "Ashdod",
    livingTown: "Haifa",
    company: "FutureVision",
    stack: "Backend",
  },
  {
    id: "6b2d8f3a-5b7d-4e8e-9f2b-8a1d3e8f7c2e",
    name: "Benjamin Ross",
    email: "benjamin.ross@example.com",
    generation: "gen Y",
    hometown: "Tel Aviv",
    livingTown: "Jerusalem",
    company: "NextGenTech",
    stack: "Full Stack",
  },
  {
    id: "9e2e8f2b-4d7d-4e8e-9f5b-8a1d3e7f7c2e",
    name: "Diana Mitchell",
    email: "diana.mitchell@example.com",
    generation: "gen X",
    hometown: "Haifa",
    livingTown: "Ashdod",
    company: "Innovatech",
    stack: "Human",
  },
  {
    id: "8d3a7f2b-5b7d-4e8e-9c2b-8a1d3e6f7c2e",
    name: "Adam Bryant",
    email: "adam.bryant@example.com",
    generation: "gen Z",
    hometown: "Beersheba",
    livingTown: "Tel Aviv",
    company: "BrightSolutions",
    stack: "Frontend",
  },
  {
    id: "7a3e8f2a-4b6d-4e8e-9f3b-8a1d3e5f7c2e",
    name: "Martha Bell",
    email: "martha.bell@example.com",
    generation: "Baby Boomers",
    hometown: "Jerusalem",
    livingTown: "Eilat",
    company: "NextGenTech",
    stack: "Backend",
  },
] as const;
